#pragma once

#include <Arduino.h>

// ESP pins:
#define MOTOR1_STEP 23
#define MOTOR2_STEP 19
#define MOTOR3_STEP 18
#define MOTOR4_STEP 5
#define MOTOR5_STEP 25
#define MOTOR6_STEP 17
#define MOTOR7_STEP 16
#define MOTOR8_STEP 4
#define MOTOR9_STEP 14
#define MOTOR10_STEP 12
#define MOTOR11_STEP 15
#define MOTOR12_STEP 13

#define SDA_PIN 21
#define SCL_PIN 22

const uint16_t motorStepPins[] = { MOTOR1_STEP, MOTOR2_STEP, MOTOR3_STEP, MOTOR4_STEP, MOTOR5_STEP, MOTOR6_STEP, MOTOR7_STEP, MOTOR8_STEP, MOTOR9_STEP, MOTOR10_STEP, MOTOR11_STEP, MOTOR12_STEP };

// i2C expander pins:
// lightsensor expander:
#define SENSOR_EXP_ADDR 0x20
#define SENSOR_PIN_OFFSET 100
#define LIGHTSENSOR1 (0 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR2 (1 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR3 (2 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR4 (3 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR5 (4 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR6 (5 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR7 (6 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR8 (7 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR9 (8 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR10 (9 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR11 (10 + SENSOR_PIN_OFFSET)
#define LIGHTSENSOR12 (11 + SENSOR_PIN_OFFSET)
#define EXPANDER_INTERRUPT_PIN 33

const uint16_t lightSensorPins[] = { LIGHTSENSOR1, LIGHTSENSOR2, LIGHTSENSOR3, LIGHTSENSOR4, LIGHTSENSOR5, LIGHTSENSOR6, LIGHTSENSOR7, LIGHTSENSOR8, LIGHTSENSOR9, LIGHTSENSOR10, LIGHTSENSOR11, LIGHTSENSOR12 };

// motor dir expander:
#define DIR_EXP_ADDR 0x21
#define MOTOR_PIN_OFFSET 200
#define MOTOR1_DIR (0 + MOTOR_PIN_OFFSET)
#define MOTOR2_DIR (1 + MOTOR_PIN_OFFSET)
#define MOTOR3_DIR (2 + MOTOR_PIN_OFFSET)
#define MOTOR4_DIR (3 + MOTOR_PIN_OFFSET)
#define MOTOR5_DIR (4 + MOTOR_PIN_OFFSET)
#define MOTOR6_DIR (5 + MOTOR_PIN_OFFSET)
#define MOTOR7_DIR (6 + MOTOR_PIN_OFFSET)
#define MOTOR8_DIR (7 + MOTOR_PIN_OFFSET)
#define MOTOR9_DIR (8 + MOTOR_PIN_OFFSET)
#define MOTOR10_DIR (9 + MOTOR_PIN_OFFSET)
#define MOTOR11_DIR (10 + MOTOR_PIN_OFFSET)
#define MOTOR12_DIR (11 + MOTOR_PIN_OFFSET)

const uint16_t motorDirPins[] = { MOTOR1_DIR, MOTOR2_DIR, MOTOR3_DIR, MOTOR4_DIR, MOTOR5_DIR, MOTOR6_DIR, MOTOR7_DIR, MOTOR8_DIR, MOTOR9_DIR, MOTOR10_DIR, MOTOR11_DIR, MOTOR12_DIR };

// config and miscellaneous expander:
#define CONFIG_EXP_ADDR 0x22
#define CONFIG_PIN_OFFSET 300
#define CONFIG_BIT_0 (0 + CONFIG_PIN_OFFSET)
#define CONFIG_BIT_1 (1 + CONFIG_PIN_OFFSET)
#define CONFIG_BIT_2 (2 + CONFIG_PIN_OFFSET)
#define CONFIG_BIT_3 (3 + CONFIG_PIN_OFFSET)
#define CONFIG_BIT_4 (4 + CONFIG_PIN_OFFSET)
#define CONFIG_BIT_5 (5 + CONFIG_PIN_OFFSET)
#define CONFIG_BIT_6 (6 + CONFIG_PIN_OFFSET)
#define CONFIG_BIT_7 (7 + CONFIG_PIN_OFFSET)
#define MOTOR_ENABLE (8 + CONFIG_PIN_OFFSET)
#define MOTORS_MS1 (9 + CONFIG_PIN_OFFSET)
#define MOTORS_MS2 (10 + CONFIG_PIN_OFFSET)
#define DEBUG_LED_1 (11 + CONFIG_PIN_OFFSET)
#define DEBUG_LED_2 (12 + CONFIG_PIN_OFFSET)
#define DEBUG_LED_3 (13 + CONFIG_PIN_OFFSET)
#define DEBUG_LED_4 (14 + CONFIG_PIN_OFFSET)

const uint16_t configBits[] = { CONFIG_BIT_0, CONFIG_BIT_1, CONFIG_BIT_2, CONFIG_BIT_3, CONFIG_BIT_4, CONFIG_BIT_5, CONFIG_BIT_6, CONFIG_BIT_7 };
const uint16_t debugLeds[] = { DEBUG_LED_1, DEBUG_LED_2, DEBUG_LED_3, DEBUG_LED_4 };